add docker compose test

diff --git a/.github/workflows/go-tests.yml b/.github/workflows/go-tests.yml
--- a/.github/workflows/go-tests.yml
+++ b/.github/workflows/go-tests.yml
@@ -27,3 +27,15 @@ jobs:
       - name: Run staticcheck
         run: |
           go tool honnef.co/go/tools/cmd/staticcheck ./internal/... ./cmd/...
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Run Docker Compose Tests
+        run: |
+          if [ ! -d "test" ]; then
+            echo "Error: test directory not found"
+            exit 1
+          fi
+          cd test
+          docker compose up --build test --exit-code-from test
